In [69]:
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np
import torch

In [113]:
class DQN(nn.Module):
    def __init__(self):
        super().__init__()
        self.input = nn.Linear(10,40)
        self.dense1 = nn.Linear(40, 40)
        self.dense2 = nn.Linear(40,20)
        self.out = nn.Linear(20, 3)

    def forward(self, x):
        x = self.input(x)
        x = F.relu(x)
        x = self.dense1(x) # flatten all dimensions except batch
        x = F.relu(x)
        x = self.dense2(x)
        x = F.relu(x)
        x = self.out(x)

        return x


net = DQN()

In [59]:
def get_state(t,window,trend):
        window = window + 1
        d = t - window + 1

        block = trend[d : t + 1] if d >= 0 else -d * [trend[0]] + trend[0 : t + 1]
        res = []
        for i in range(window - 1):
            res.append(block[i + 1] - block[i])
        return [res]

In [60]:
df = pd.read_csv('./GOOG.csv')

In [61]:
df.head()
print(len(df))

23


In [62]:
differenced = []
window = 10
data = df["Close"].tolist()

for i in range(len(df)):
    differenced.append(get_state(i,window,data))
    


In [91]:
print(len(differenced))
train = np.array(differenced[0:20])
print(len(train))
test = np.array(differenced[20:])
label = np.random.rand(20,3)
print(label)
print(len(label))

23
20
[[0.33755867 0.72779034 0.72180801]
 [0.0628445  0.98713083 0.03589424]
 [0.85363061 0.56125581 0.92619915]
 [0.88284218 0.94432469 0.94805774]
 [0.66827644 0.20404391 0.55598035]
 [0.1938484  0.76880698 0.92172592]
 [0.6490194  0.43146837 0.04701077]
 [0.61348474 0.74600726 0.99957052]
 [0.95972203 0.55954448 0.30462556]
 [0.21266835 0.90908491 0.11874575]
 [0.14832179 0.88999314 0.41063467]
 [0.21368983 0.1855977  0.97814354]
 [0.95735246 0.68513999 0.66149524]
 [0.81327013 0.74454189 0.21820827]
 [0.7281261  0.3380345  0.50896426]
 [0.91619257 0.8213553  0.32473443]
 [0.0212847  0.41022182 0.45062052]
 [0.05192477 0.46215348 0.49596166]
 [0.15383206 0.11099178 0.56142245]
 [0.28306571 0.4358125  0.50654556]]
20


In [92]:
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [114]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i in range(20):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = torch.FloatTensor(train[i]),torch.FloatTensor(label[i])

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        out1,out2,out3 = net(inputs[0])
        print(label[i])
        print(outputs[0])
        loss = criterion(out1, label[i,0]) + criterion(out2, label[0][i,1]) + criterion(out3, label[0][i,2])
        
        loss.backward()
        optimizer.step()
        running_loss += loss.item()


[0.33755867 0.72779034 0.72180801]
tensor([0.3189, 0.5163, 0.5517], grad_fn=<SelectBackward0>)


TypeError: 'int' object is not callable